# Numpy: Package for Multidimensional array

## create an array

In [2]:
import numpy as np

In [42]:
sample_list =[1,2,3,5,8,9,6,4,6,2,5,6,1]
np.array(sample_list)

array([1, 2, 3, 5, 8, 9, 6, 4, 6, 2, 5, 6, 1])

In [41]:
arr=np.array(sample_list)
arr

array([1, 2, 3, 5, 8, 9, 6, 4, 6, 2, 5, 6, 1])

In [5]:
print(arr[2:6])             #print(arr[index1:index2])

[3 5 8 9]


In [6]:
multi_list =[4,5,6],[7,8,9],[10,11,12]
np.array(multi_list)

array([[ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [7]:
arr1=np.array(multi_list)
arr1

array([[ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [8]:
np.arange(100,110)     #starts with 100 and end with (number-1) i.e 110-1=109

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109])

In [46]:
np.arange(10,90,8)    #(start number ,end number , difference(10,10+8,10+8+8....)) 

array([10, 18, 26, 34, 42, 50, 58, 66, 74, 82])

In [10]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [11]:
np.zeros(10,dtype=int)     #dtype=int makes float into int

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [12]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [13]:
np.ones(5,dtype=int)     #dtype=int makes float into int

array([1, 1, 1, 1, 1])

In [14]:
a=np.ones((2,5))         #((no.of list,no. of repeatation))

In [15]:
np.ones((2,5),dtype=int)      #dtype=int makes float into int

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [16]:
a=np.ones((2,5),dtype=int)         
b=np.zeros((3,4),dtype=int)
print(a,b)

[[1 1 1 1 1]
 [1 1 1 1 1]] [[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [17]:
np.linspace(0,1,5)     #it divide 0 to 1 into 5 parts including 0 and 1

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [48]:
np.linspace(0,10,20,dtype=int)    #dtype=int makes a restriction of every numeric value to be int so the float values appear to be coming in int form

array([ 0,  0,  1,  1,  2,  2,  3,  3,  4,  4,  5,  5,  6,  6,  7,  7,  8,
        8,  9, 10])

In [19]:
np.eye(5,dtype=int)       

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [20]:
np.eye(6,10,dtype=int)         #(6,10)-->(6 no of list/rows of list,list of 10 values)

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0]])

In [95]:
np.random.rand(2,5)           #(2,4)->(no. of list,no. of element in the list)

array([[0.70246108, 0.42842323, 0.49548795, 0.22506196, 0.25084293],
       [0.40664432, 0.94082203, 0.82387503, 0.96004579, 0.04325514]])

In [22]:
np.random.randn(2,5)           #(2,4)->(no. of list,no. of element in the list)

array([[ 0.44899264, -0.95302831,  0.50022225, -0.10503055, -0.76607732],
       [-0.35189617,  0.81899348,  0.066062  ,  0.11756413, -0.62926734]])

In [28]:
np.random.randint(0,10,20,dtype=int)      #(start,end,number of elements in the list)

array([6, 1, 0, 0, 4, 8, 5, 7, 3, 5, 2, 2, 2, 8, 4, 9, 2, 8, 5, 5])

In [29]:
arr

array([1, 2, 3, 5, 8, 9, 6, 4, 6, 2, 5, 6, 1])

In [82]:
ar=np.random.randint(5,15,10)
v=ar.min()
u=ar.max()
print(v,",",u)

5 , 14


In [83]:
ar

array([ 6,  8, 11, 11,  9, 14,  7,  5, 12,  8])

In [85]:
ar.argmin()

7

In [75]:
ar1=[1,5,65,2,4,1,458,0,4,48,123,1,4,6,5,9,6,5]
ar1

[1, 5, 65, 2, 4, 1, 458, 0, 4, 48, 123, 1, 4, 6, 5, 9, 6, 5]

In [76]:
ar2=np.array(ar1)
ar2.argmin()

7

In [87]:
ar2

array([  1,   5,  65,   2,   4,   1, 458,   0,   4,  48, 123,   1,   4,
         6,   5,   9,   6,   5])

In [120]:
am=np.random.rand(3,1,4)
am

array([[[0.38794856, 0.55310997, 0.28475951, 0.09202473]],

       [[0.82704095, 0.89814024, 0.61804865, 0.83517712]],

       [[0.53470504, 0.91800106, 0.63632176, 0.31349107]]])

In [121]:
am.T           # .T  --> transpose

array([[[0.38794856, 0.82704095, 0.53470504]],

       [[0.55310997, 0.89814024, 0.91800106]],

       [[0.28475951, 0.61804865, 0.63632176]],

       [[0.09202473, 0.83517712, 0.31349107]]])

In [125]:
an=am.reshape(3,4)
an                                                     #it  rearrange the matric (nxm)

array([[0.38794856, 0.55310997, 0.28475951, 0.09202473],
       [0.82704095, 0.89814024, 0.61804865, 0.83517712],
       [0.53470504, 0.91800106, 0.63632176, 0.31349107]])

In [127]:
abc=np.arange(0,100)
abc

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [129]:
abc[1:5]=1000000
abc

array([      0, 1000000, 1000000, 1000000, 1000000,       5,       6,
             7,       8,       9,      10,      11,      12,      13,
            14,      15,      16,      17,      18,      19,      20,
            21,      22,      23,      24,      25,      26,      27,
            28,      29,      30,      31,      32,      33,      34,
            35,      36,      37,      38,      39,      40,      41,
            42,      43,      44,      45,      46,      47,      48,
            49,      50,      51,      52,      53,      54,      55,
            56,      57,      58,      59,      60,      61,      62,
            63,      64,      65,      66,      67,      68,      69,
            70,      71,      72,      73,      74,      75,      76,
            77,      78,      79,      80,      81,      82,      83,
            84,      85,      86,      87,      88,      89,      90,
            91,      92,      93,      94,      95,      96,      97,
            98,     

## two dimensional array

In [130]:
import numpy as np

In [131]:
sample=np.array([[21,51,54,15],[15,6,8,58],[15,28,64,95]])
sample

array([[21, 51, 54, 15],
       [15,  6,  8, 58],
       [15, 28, 64, 95]])

In [134]:
sample[2][1]                #sample[index in row-wise][index in column-wise]

28

In [254]:
sample[0:,2:]              # [0:,2:] --> 0: from the index zero row and 2: from index 2nd column

array([[54, 15],
       [ 8, 58],
       [64, 95]])

In [146]:
sample[1:,3:]

array([[58],
       [95]])

In [151]:
sample[0:2,1:3]

array([[51, 54],
       [ 6,  8]])

In [162]:
sam=np.arange(0,100)
sam

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [163]:
sam.min()           #minimum

0

In [255]:
sam.max()            #maximum

99

In [165]:
sam.argmin()

0

In [166]:
sam.argmax()

99

In [170]:
sam+sam

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100, 102,
       104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126, 128,
       130, 132, 134, 136, 138, 140, 142, 144, 146, 148, 150, 152, 154,
       156, 158, 160, 162, 164, 166, 168, 170, 172, 174, 176, 178, 180,
       182, 184, 186, 188, 190, 192, 194, 196, 198])

In [171]:
sam-sam

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [174]:
sam*sam

array([   0,    1,    4,    9,   16,   25,   36,   49,   64,   81,  100,
        121,  144,  169,  196,  225,  256,  289,  324,  361,  400,  441,
        484,  529,  576,  625,  676,  729,  784,  841,  900,  961, 1024,
       1089, 1156, 1225, 1296, 1369, 1444, 1521, 1600, 1681, 1764, 1849,
       1936, 2025, 2116, 2209, 2304, 2401, 2500, 2601, 2704, 2809, 2916,
       3025, 3136, 3249, 3364, 3481, 3600, 3721, 3844, 3969, 4096, 4225,
       4356, 4489, 4624, 4761, 4900, 5041, 5184, 5329, 5476, 5625, 5776,
       5929, 6084, 6241, 6400, 6561, 6724, 6889, 7056, 7225, 7396, 7569,
       7744, 7921, 8100, 8281, 8464, 8649, 8836, 9025, 9216, 9409, 9604,
       9801])

In [185]:
(sam/sam)

C:\Users\hp\AppData\Local\Temp/ipykernel_13616/47703593.py:1: RuntimeWarning: invalid value encountered in true_divide
  (sam/sam)


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [187]:
np.exp(sam)      #exponential

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04,
       1.62754791e+05, 4.42413392e+05, 1.20260428e+06, 3.26901737e+06,
       8.88611052e+06, 2.41549528e+07, 6.56599691e+07, 1.78482301e+08,
       4.85165195e+08, 1.31881573e+09, 3.58491285e+09, 9.74480345e+09,
       2.64891221e+10, 7.20048993e+10, 1.95729609e+11, 5.32048241e+11,
       1.44625706e+12, 3.93133430e+12, 1.06864746e+13, 2.90488497e+13,
       7.89629602e+13, 2.14643580e+14, 5.83461743e+14, 1.58601345e+15,
       4.31123155e+15, 1.17191424e+16, 3.18559318e+16, 8.65934004e+16,
       2.35385267e+17, 6.39843494e+17, 1.73927494e+18, 4.72783947e+18,
       1.28516001e+19, 3.49342711e+19, 9.49611942e+19, 2.58131289e+20,
       7.01673591e+20, 1.90734657e+21, 5.18470553e+21, 1.40934908e+22,
       3.83100800e+22, 1.04137594e+23, 2.83075330e+23, 7.69478527e+23,
      

In [256]:
np.sqrt(sam)    #square root

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595, 4.58257569, 4.69041576, 4.79583152, 4.89897949,
       5.        , 5.09901951, 5.19615242, 5.29150262, 5.38516481,
       5.47722558, 5.56776436, 5.65685425, 5.74456265, 5.83095189,
       5.91607978, 6.        , 6.08276253, 6.164414  , 6.244998  ,
       6.32455532, 6.40312424, 6.4807407 , 6.55743852, 6.63324958,
       6.70820393, 6.78232998, 6.8556546 , 6.92820323, 7.        ,
       7.07106781, 7.14142843, 7.21110255, 7.28010989, 7.34846923,
       7.41619849, 7.48331477, 7.54983444, 7.61577311, 7.68114575,
       7.74596669, 7.81024968, 7.87400787, 7.93725393, 8.        ,
       8.06225775, 8.1240384 , 8.18535277, 8.24621125, 8.30662386,
       8.36660027, 8.42614977, 8.48528137, 8.54400375, 8.60232

In [258]:
np.log(sam)          #log

C:\Users\hp\AppData\Local\Temp/ipykernel_13616/3925996257.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(sam)          #log


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509, 2.39789527, 2.48490665, 2.56494936, 2.63905733,
       2.7080502 , 2.77258872, 2.83321334, 2.89037176, 2.94443898,
       2.99573227, 3.04452244, 3.09104245, 3.13549422, 3.17805383,
       3.21887582, 3.25809654, 3.29583687, 3.33220451, 3.36729583,
       3.40119738, 3.4339872 , 3.4657359 , 3.49650756, 3.52636052,
       3.55534806, 3.58351894, 3.61091791, 3.63758616, 3.66356165,
       3.68887945, 3.71357207, 3.73766962, 3.76120012, 3.78418963,
       3.80666249, 3.8286414 , 3.8501476 , 3.87120101, 3.8918203 ,
       3.91202301, 3.93182563, 3.95124372, 3.97029191, 3.98898405,
       4.00733319, 4.02535169, 4.04305127, 4.06044301, 4.07753744,
       4.09434456, 4.11087386, 4.12713439, 4.14313473, 4.15888308,
       4.17438727, 4.18965474, 4.20469262, 4.21950771, 4.2341065 ,
       4.24849524, 4.26267988, 4.27666612, 4.29045944, 4.30406

In [192]:
np.argmax(sam)

99

In [193]:
np.argmin(sam)

0

In [194]:
np.std(sam)         #standard deviaton

28.86607004772212

In [259]:
np.var(sam)         #variance

833.25

In [196]:
np.mean(sam)

49.5

In [197]:
np.median(sam)

49.5

In [203]:
x=np.random.rand(4,5)
x

array([[0.33016572, 0.61428774, 0.10928338, 0.62499703, 0.4298781 ],
       [0.62302348, 0.56349253, 0.67985279, 0.06332458, 0.6005075 ],
       [0.55071617, 0.45930651, 0.15661494, 0.25022615, 0.52372281],
       [0.47862906, 0.66459866, 0.28747259, 0.20021481, 0.99832621]])

In [260]:
np.round(x,decimals=4)          #rounding off to 4 decimal places in x

array([[0.3302, 0.6143, 0.1093, 0.625 , 0.4299],
       [0.623 , 0.5635, 0.6799, 0.0633, 0.6005],
       [0.5507, 0.4593, 0.1566, 0.2502, 0.5237],
       [0.4786, 0.6646, 0.2875, 0.2002, 0.9983]])

In [261]:
fruit=np.array(["apple","mango","apple","orange","Orange"])
np.unique(fruit)                                         #printing the unique (no repeats)

array(['Orange', 'apple', 'mango', 'orange'], dtype='<U6')

# Pandas

In [262]:
import pandas as pd                        #importing  pandas

In [263]:
import numpy as np

### Pandas dataframe and indexing

In [215]:
sport=pd.Series([1,2,3,4],index=['cricket','football','basketball','golf'])      #INDEXING
sport

cricket       1
football      2
basketball    3
golf          4
dtype: int64

In [216]:
sport1=pd.Series([11,12,3,51],index=['cricket','baseball','skating','football'])
sport1

cricket     11
baseball    12
skating      3
football    51
dtype: int64

In [217]:
sport+sport1  #combinning two dataset requires existance of same index in both like both should have basketball but don't have i.e NAN has came 

baseball       NaN
basketball     NaN
cricket       12.0
football      53.0
golf           NaN
skating        NaN
dtype: float64

In [226]:
df=pd.DataFrame(np.random.rand(8,7),index='A B C D E F G H'.split(),columns='Sc1 Sc2 Sc3 Sc4 Sc5 Sc6 Sc7'.split())
df                         #DataFrame

Sc1       Sc2       Sc3       Sc4       Sc5       Sc6       Sc7
A  0.956572  0.229744  0.692706  0.532051  0.142405  0.515052  0.785464
B  0.572901  0.046835  0.538890  0.293328  0.230481  0.824555  0.409241
C  0.125329  0.478156  0.491865  0.224052  0.216096  0.441460  0.426723
D  0.167127  0.365165  0.825469  0.215996  0.119130  0.314497  0.604156
E  0.595408  0.554467  0.928439  0.466070  0.570004  0.820732  0.239546
F  0.675163  0.210378  0.696592  0.129543  0.040413  0.793706  0.204617
G  0.571912  0.819112  0.157242  0.563482  0.161405  0.469502  0.683713
H  0.873982  0.170695  0.317635  0.003499  0.467963  0.297448  0.649227

In [229]:
df[['Sc1','Sc5','Sc3']]               #calling Data from the Dataframe via columns

Sc1       Sc5       Sc3
A  0.956572  0.142405  0.692706
B  0.572901  0.230481  0.538890
C  0.125329  0.216096  0.491865
D  0.167127  0.119130  0.825469
E  0.595408  0.570004  0.928439
F  0.675163  0.040413  0.696592
G  0.571912  0.161405  0.157242
H  0.873982  0.467963  0.317635

In [231]:
df['Sc1']

A    0.956572
B    0.572901
C    0.125329
D    0.167127
E    0.595408
F    0.675163
G    0.571912
H    0.873982
Name: Sc1, dtype: float64

In [264]:
df['Sc9']=df['Sc1']+df['Sc3']
df[['Sc1','Sc3','Sc9']]                 #adding of different columns and making plus adding new column

Sc1       Sc3       Sc9
A  0.956572  0.692706  1.649278
B  0.572901  0.538890  1.111791
C  0.125329  0.491865  0.617194
D  0.167127  0.825469  0.992596
E  0.595408  0.928439  1.523847
F  0.675163  0.696592  1.371754
G  0.571912  0.157242  0.729155
H  0.873982  0.317635  1.191618

In [242]:
df

Sc1       Sc2       Sc3       Sc4       Sc5       Sc6       Sc7  \
A  0.956572  0.229744  0.692706  0.532051  0.142405  0.515052  0.785464   
B  0.572901  0.046835  0.538890  0.293328  0.230481  0.824555  0.409241   
C  0.125329  0.478156  0.491865  0.224052  0.216096  0.441460  0.426723   
D  0.167127  0.365165  0.825469  0.215996  0.119130  0.314497  0.604156   
E  0.595408  0.554467  0.928439  0.466070  0.570004  0.820732  0.239546   
F  0.675163  0.210378  0.696592  0.129543  0.040413  0.793706  0.204617   
G  0.571912  0.819112  0.157242  0.563482  0.161405  0.469502  0.683713   
H  0.873982  0.170695  0.317635  0.003499  0.467963  0.297448  0.649227   

        Sc9  
A  1.649278  
B  1.111791  
C  0.617194  
D  0.992596  
E  1.523847  
F  1.371754  
G  0.729155  
H  1.191618

In [265]:
df.drop('H')                  #dropping row H via ( .drop(''))

Sc1       Sc2       Sc3       Sc4       Sc5       Sc6       Sc7  \
A  0.956572  0.229744  0.692706  0.532051  0.142405  0.515052  0.785464   
B  0.572901  0.046835  0.538890  0.293328  0.230481  0.824555  0.409241   
C  0.125329  0.478156  0.491865  0.224052  0.216096  0.441460  0.426723   
D  0.167127  0.365165  0.825469  0.215996  0.119130  0.314497  0.604156   
E  0.595408  0.554467  0.928439  0.466070  0.570004  0.820732  0.239546   
F  0.675163  0.210378  0.696592  0.129543  0.040413  0.793706  0.204617   
G  0.571912  0.819112  0.157242  0.563482  0.161405  0.469502  0.683713   

        Sc9  
A  1.649278  
B  1.111791  
C  0.617194  
D  0.992596  
E  1.523847  
F  1.371754  
G  0.729155

In [266]:
df.drop("Sc1",axis=1)         #dropping column Sc1 via calling (.drop('',axis=1)) [axis=1 for column and axis=0 for row] 

Sc2       Sc3       Sc4       Sc5       Sc6       Sc7       Sc9
A  0.229744  0.692706  0.532051  0.142405  0.515052  0.785464  1.649278
B  0.046835  0.538890  0.293328  0.230481  0.824555  0.409241  1.111791
C  0.478156  0.491865  0.224052  0.216096  0.441460  0.426723  0.617194
D  0.365165  0.825469  0.215996  0.119130  0.314497  0.604156  0.992596
E  0.554467  0.928439  0.466070  0.570004  0.820732  0.239546  1.523847
F  0.210378  0.696592  0.129543  0.040413  0.793706  0.204617  1.371754
G  0.819112  0.157242  0.563482  0.161405  0.469502  0.683713  0.729155
H  0.170695  0.317635  0.003499  0.467963  0.297448  0.649227  1.191618

In [247]:
df.drop('A',axis=0)

Sc1       Sc2       Sc3       Sc4       Sc5       Sc6       Sc7  \
B  0.572901  0.046835  0.538890  0.293328  0.230481  0.824555  0.409241   
C  0.125329  0.478156  0.491865  0.224052  0.216096  0.441460  0.426723   
D  0.167127  0.365165  0.825469  0.215996  0.119130  0.314497  0.604156   
E  0.595408  0.554467  0.928439  0.466070  0.570004  0.820732  0.239546   
F  0.675163  0.210378  0.696592  0.129543  0.040413  0.793706  0.204617   
G  0.571912  0.819112  0.157242  0.563482  0.161405  0.469502  0.683713   
H  0.873982  0.170695  0.317635  0.003499  0.467963  0.297448  0.649227   

        Sc9  
B  1.111791  
C  0.617194  
D  0.992596  
E  1.523847  
F  1.371754  
G  0.729155  
H  1.191618

In [267]:
df.drop(['Sc1','Sc2'],axis=1)          #dropping two columns simultaneously

Sc3       Sc4       Sc5       Sc6       Sc7       Sc9
A  0.692706  0.532051  0.142405  0.515052  0.785464  1.649278
B  0.538890  0.293328  0.230481  0.824555  0.409241  1.111791
C  0.491865  0.224052  0.216096  0.441460  0.426723  0.617194
D  0.825469  0.215996  0.119130  0.314497  0.604156  0.992596
E  0.928439  0.466070  0.570004  0.820732  0.239546  1.523847
F  0.696592  0.129543  0.040413  0.793706  0.204617  1.371754
G  0.157242  0.563482  0.161405  0.469502  0.683713  0.729155
H  0.317635  0.003499  0.467963  0.297448  0.649227  1.191618

In [273]:
df2={'ID':[1,2,3,4,5,6],'Name':['ram','ramu','raj','raju','ramesh','rakesh'],'Profit':[123,156,148,156,127,158]}
df1=pd.DataFrame(df2)
df1                                      #dictionary

ID    Name  Profit
0   1     ram     123
1   2    ramu     156
2   3     raj     148
3   4    raju     156
4   5  ramesh     127
5   6  rakesh     158

In [274]:
df1.drop('ID',axis=1)

Name  Profit
0     ram     123
1    ramu     156
2     raj     148
3    raju     156
4  ramesh     127
5  rakesh     158

In [275]:
df1['Name']

0       ram
1      ramu
2       raj
3      raju
4    ramesh
5    rakesh
Name: Name, dtype: object

In [282]:
df3=pd.read_csv('abc.csv')                  # to read cdv file or for excel[pd.read_excel('')]

FileNotFoundError: [Errno 2] No such file or directory: 'abc.csv'

In [283]:
df3.head

NameError: name 'df3' is not defined

### Assignment

In [287]:
nv=np.zeros(10,dtype=int)                #null vector size 10
nv

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [289]:
nv[4]=1
nv

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

In [302]:
nv1=np.arange(10,65)
nv1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
       61, 62, 63, 64])

In [310]:
nv1=np.arange(64,9,-1)
nv1                               #reverse of above matrix/list

array([64, 63, 62, 61, 60, 59, 58, 57, 56, 55, 54, 53, 52, 51, 50, 49, 48,
       47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32, 31,
       30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14,
       13, 12, 11, 10])

In [313]:
nv2=np.arange(0,9).reshape(3,3)
nv2

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])